/** Stable React Query keys — auth lives in the fetcher, not the key. */
export const QK = {
  rides: ["rides"] as const,
  deliveries: ["deliveries"] as const,
  riders: ["riders"] as const,
  passengers: ["passengers"] as const,
  userStats: ["admin-user-stats"] as const,
  opsSummary: ["admin-ops-summary"] as const,
  financeSummary: ["admin-finance-summary"] as const,
  walletTx: ["admin-wallet-transactions"] as const,
  payoutRequests: ["admin-payout-requests"] as const,
  ratings: ["admin-ratings"] as const,
  incidents: ["admin-incidents"] as const,
  adminAccounts: ["admin-accounts"] as const,
  adminPermissions: ["admin-permissions"] as const,
  adminModules: ["admin-modules"] as const,
  zones: ["service-zones"] as const,
  auditLogs: ["admin-audit-logs"] as const,
  supportTickets: ["admin-support-tickets"] as const,
  ticketMessages: (ticketId: string) => ["admin-ticket-messages", ticketId] as const,
  escalationRules: ["admin-escalation-rules"] as const,
  scheduledBroadcasts: ["admin-scheduled-broadcasts"] as const,
  opsJobStatus: ["admin-ops-jobs-status"] as const,
  riderDocuments: ["admin-rider-documents"] as const,
  platformSettings: ["admin-platform-settings"] as const,
  promoCodes: ["admin-promo-codes"] as const,
  goPointRules: ["admin-go-point-rules"] as const,
  goPointBalances: ["admin-go-point-balances"] as const,
  goPointLedger: ["admin-go-point-ledger"] as const,
  goPointRedemptions: ["admin-go-point-redemptions"] as const,
  messageTemplates: ["admin-message-templates"] as const,
  activeRides: ["admin-active-rides"] as const,
  availableRiders: (rideId: string) => ["admin-available-riders", rideId] as const,
  assignmentHistory: (rideId: string) => ["admin-assignment-history", rideId] as const,
  assignmentStats: ["admin-assignment-stats"] as const,
  assignmentRules: ["admin-assignment-rules"] as const,
  assignmentAuditLogs: ["admin-assignment-audit-logs"] as const,
  allAssignmentHistory: ["admin-all-assignment-history"] as const,
  rideTimeline: (rideId: string) => ["admin-ride-timeline", rideId] as const
} as const;
